### ISSUE TITLE
Human training data

### ISSUE THREAD

**Issue by rajinder4489** [pcahan1/CellNet#6]
I am trying to get more information on the training data that is used for humans. From the Robject that you have provided it gives the SRA ids and I am not able to get more information from them computationally and I donot want to spend my time searching for each id  manually.

It would be really helpful if you could provide more insights into the data that was used to train the system.
In particular I'm interested in knowing the diseased states of the models and _in vitro_ or biopsies  used.

Thanks

**Comment by pcahan1** [comment]
Hi,

Thanks much for the interest in using CellNet.  Attached here is a spreadsheet containing all of the annotation information for the sample data that went into the Human training data dated June 20th, 2017.

Please let us know if you need any more information. Thanks!

Best,

Patrick

[human_healthy_training.xlsx](https://github.com/pcahan1/CellNet/files/2129180/human_healthy_training.xlsx)

**Comment by rajinder4489** [comment]
Thank you very much Patrick
This information is very helpful.

Rajinder
