### ISSUE TITLE
cn_salmon error

### ISSUE THREAD

**Issue by masruralam** [pcahan1/CellNet#7]
Hi,
I've been trying to use Cellnet following the protocols from the article in Nature. I am using the the mouse training data. However I seem to be stuck on the same step using expList<-cn_salmon(stQuery) and it generates this error:

In file(file, "rt") : 
   cannot open file './salmonRes_SRR2070926/quant.sf': No such file or directory

I also tried this with the human data and it generated a similar message. 

Thanks

**Comment by pcahan1** [comment]
We have fixed this bug in the latest version (0.1.1). Please try analyzing the demonstration data again after installing the latest version. We have also posted an updated EC2 image, and have updated the walk thru here on Gitub. Thank you!
